// Generated by CoffeeScript 1.6.3
window.Map = {
  opening: {
    sc: 'street',
    t: '    I felt quite lucky this morning. But now Im just a doll sitting on this rotten bus for hours. I may as well leave now, the bus isnt gonna go anywhere in the near future. I think the driver is asleep, but its possible that he isnt even on the bus.'
  },
  gabba: {
    dance: {
      'to music': '4/4/4/4/4',
      'to waves': 'whoohoooo',
      'till sunrise': 'you dance till the sun comes up and your eyes cant bear the rise'
    }
  },
  street: {
    go: {
      'to work': 'i dont really need that',
      'to a friends house': 'i cant go there, its too soon.',
      'home': 'i guess im already there'
    },
    'don\'t': {
      'go anywhere and wait': 'finally a good idea!',
      'do nothing': 'nothing so painful'
    },
    download: {
      'some shit': {
        t: '    i get some acid playing in my ears in a minute',
        set: {
          street: {
            go: {
              'gabba': {
                t: '<br>***<br><br>okay, lets do it!',
                scene: 'gabba'
              },
              'eki': 'para'
            }
          }
        },
        del: {
          street: {
            go: 'to work'
          }
        }
      },
      'the link': 'i \ntype my password in, and after a second im looking at my stats'
    }
  }
};
